openapi: 3.0.0

info:
  title: Premium Al Image Upscaler API
  version: 0.1.9

servers:
  - url: https://premium-ai-image-upscaler-api-production.up.railway.app
    description: Production server

paths:
  /upscale:
    get:
      summary: Upscale and enhance an image
      description: Takes an image URL and prompt to enhance and upscale the image using AI. Returns a JSON response with the base64-encoded image.
      parameters:
        - name: image_url
          in: query
          required: true
          schema:
            type: string
          description: URL of the image to process
          example: "https://storage.googleapis.com/apihub85/0_1.webp"
        - name: prompt
          in: query
          required: true
          schema:
            type: string
          description: Prompt to guide the AI enhancement
          example: "UHD 4k vogue style"
      responses:
        "200":
          description: Successfully processed image
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  image:
                    type: string
                    description: Base64-encoded PNG image
                  format:
                    type: string
